### ISSUE TITLE
Cannot Edit Meta Keyword and Description 4.6.0beta1

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#2084]
This problem I found from SEO settings page and even to all include app like Videos, Music and Photos. You cannot edit the Meta Keywoed and Description. After hit the "Click Here" menu to start edit the description or meta keyword, tha page automatically redirect to Dashboard.

**Comment by neil96** [comment]
Thanks @juniortimeline ,

I can reproduce on upgrade site. Thanks for your report.

Regards.

**Comment by Foxgerman** [comment]
The same issue is on Captcha setting. By the way the devs should be remove any season ids from language pack

`<title>Captcha Font</title><info>Select which TTF (True Type Font) you would like to use for your Captcha image.<br><br>Note the setting <a href="admincp/setting/search/?sessionid=5a3636e935dbe?var=captcha_font">Captcha Font</a> must be enabled in order to use this option.</info>`

**Comment by neil96** [comment]
@Foxgerman ,

> The same issue is on Captcha setting. By the way the devs should be remove any session ids from language pack


We fixed this issue on 4.6.0. Thanks for you report.

Regards.

**Comment by spirogg** [comment]
how to fix this please, new install 4.6.0 and its still doing this on my site for SEO settings page

**Comment by juniortimeline** [comment]
@spirogg I still facing this problem but this is another trick using phrase

1. copy the SEO variable ex. seo_pages_meta_description
2. paste on "search" of Phrase page
3. click "View More Search Options"
4. select "Phrase Variable Name Only"
5. Click "Submit" and you can edit now the Description or Keywords

**Comment by spirogg** [comment]
@neil96 is there another fix ? 

@juniortimeline thank you for that Idea :)

**Comment by juniortimeline** [comment]
@spirogg  welcome 😃
